### PR TITLE
improve concurrency capabilitites of JMS

### PR DESCRIPTION
**Pull request by davidkarlsen**
This PR tries to avoid getting ConcurrentModificationExceptions by using threadsafe collection types

### CODE REVIEW

**Comment by InfoSec812** [comment]
I don't see any issues with this change. @cemartins, would you review and confirm as you are able?

**Comment by davidkarlsen** [comment]
Any update on this?

**Comment by cemartins** [comment]
Sorry mate. Was out for some time. I'll do this now

**Comment by cemartins** [comment]
The merge is completed but I can only make a release later today (cannot publish to maven central from office computer because of the proxy crap)

**Comment by davidkarlsen** [comment]
Awesome - thanks!

**Comment by cemartins** [comment]
Done - just released new version 1.0.7

**Pull request merged**
