### PR TITLE
add ability to add rows by map

### PR DESCRIPTION
**Pull request by DwordPtr**
This kinda looks like it's clashing with the original purpose of the library, so It's likely going to need some revision, but here's a way to add a row with a HashMap

### CODE REVIEW

**Comment by InfoSec812** [comment]
Thanks much for the PR... Would you mind updating the associated unit tests so that the CI build will succeed?

**Comment by DwordPtr** [comment]
@InfoSec812 Are there any changes you'd like me to make?
I'm not too knowledgeable about your code review process.

**Comment by InfoSec812** [comment]
I'm actually a committer, and even I am not sure of the review process. The
CircleCI configuration is new to me. We'll have to wait for Carlos to chime
in.

**Comment by cemartins** [comment]
I'd say, If it's working then accept the pull request. We'll deal with
CircleCI later on. I think there's a bug in the configuration of CircleCi.
I'm on Holidays til next Tuesday. I'll only be able to look at it after I
come back.

Cheers guys

**Comment by DwordPtr** [comment]
@cemartins are you still on holiday?

**Comment by cemartins** [comment]
No. I'm back. I'll look into it tonight

**Comment by cemartins** [comment]
Tested locally. All tests passed

**Comment by cemartins** [comment]
Changes made available in the new mockrunner-1.1.2 release http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.mockrunner%22

**Pull request merged**
