### PR TITLE
JMS Test Module should create Queues/Topics automatically

### PR DESCRIPTION
**Pull request by greyfairer**
See #30 

getTopic()/getQueue() should auto-create the topic/queue if it doesn't exist yet.

Takes care of race conditions too, if two threads concurrently write to the same auto-created queue, they're guaranteed to get the same one.

The JMSTestModule.checkQueue/TopicByName should not auto-create IMHO, so that's changed, too.

### CODE REVIEW

**Comment by cemartins** [comment]
Hello Greyfairer,

Your pull request breaks test cases MockQueueSessionTest.testCreateQueues() and MockTopicSessionTest.testCreateTopics()

Is it because these tests are no longer relevant? Should they be removed?

**Comment by greyfairer** [comment]
Oops, hadn't noticed that. I started from the subversion code base like two years ago, we used this patch at one client, but decided to contribute it back only recently.

The tests probably fail because they expect an exception when it tries to get a queue that was not created explicitly. Which is indeed exactly what was changed. So I should remove that bit from the tests. I'll see about that tomorrow.

**Comment by cemartins** [comment]
Great! Thank you. I'll merge your code after that. It's a good contribution.

**Comment by cemartins** [comment]
Hello @greyfairer,

Did you manage to se about the broken tests after your update? I would like to make a new release with your update and another fix that was made for the JDBC module.

Thanks

**Comment by greyfairer** [comment]
Tests fixed, sorry for the delay, busy week at work...

**Comment by cemartins** [comment]
No problem, that's actually great. I can do the release later today.
Cheers.

**Pull request merged**
